### PR TITLE
Encryption seems broken

### PR DESCRIPTION
**Pull request by bricestacey**
I am trying to use lightpush with asymmetric encryption, but am getting the following error when trying to send a message:

```
json: cannot unmarshal string into Go struct field WakuMessage.timestamp of type int64
```

Since timestamp is optional, I go ahead and remove it and the message is published.

I'm reading the message from a store, but when I call `decodeAsymmetric` I am getting this message:

```
json: cannot unmarshal object into Go struct field WakuMessage.payload of type []uint8
```

Here is an example repo that demonstrates the issue https://github.com/waku-org/waku-react-native/compare/master...bricestacey:waku-react-native:encrypt-bug

I have successfully used lightpush without encryption, so I know that part is working. Relay encryption also breaks.

the message that I get from the store looks like this:

```
{"contentTopic": "chat", "payload": [4, 73, 59, 4, 88, 194, 41, 97, 59, 66, 51, 216, 127, 79, 53, 76, 142, 67, 69, 163, 83, 42, 82, 58, 71, 135, 54, 70, 234, 227, 74, 66, 147, 147, 140, 6, 226, 136, 127, 136, 50, 226, 12, 4, 222, 21, 114, 56, 36, 124, 121, 18, 196, 192, 156, 127, 174, 204, 100, 121, 155, 149, 208, 221, 12, 29, 69, 217, 155, 18, 232, 211, 1, 25, 248, 244, 158, 7, 195, 206, 184, 99, 169, 145, 248, 120, 170, 218, 128, 218, 139, 246, 44, 169, 170, 217, 140, 205, 85, 56, 224, 114, 159, 61, 144, 60, 34, 101, 87, 98, 25, 116, 178, 55, 106, 33, 107, 35, 107, 82, 154, 234, 96, 48, 11, 47, 255, 65, 162, 60, 25, 163, 139, 8, 99, 220, 20, 46, 36, 62, 147, 10, 159, 124, 103, 82, 207, 47, 219, 246, 206, 105, 55, 57, 23, 15, 22, 138, 21, 83, 247, 152, 147, 248, 64, 139, 34, 147, 21, 61, 73, 46, 183, 81, 148, 135, 242, 64, 57, 51, 123, 34, 185, 167, 130, 248, 238, 59, 249, 61, 64, 15, 26, 78, 177, 15, 100, 156, 112, 132, 127, 28, 104, 225, 70, 215, 85, 216, 253, 120, 98, 175, 102, 165, 90, 129, 138, 141, 164, 159, 9, 154, 45, 216, 155, 100, 240, 28, 13, 64, 243, 53, 177, 148, 192, 7, 74, 204, 226, 18, 144, 21, 53, 85, 204, 157, 165, 103, 202, 246, 72, 56, 143, 43, 67, 67, 90, 47, 37, 136, 76, 83, 135, 163, 226, 112, 251, 201, 239, 97, 128, 10, 184, 17, 123, 214, 164, 131, 22, 134, 86, 41, 217, 244, 50, 27, 117, 15, 53, 151, 73, 225, 77, 87, 60, 21, 21, 19, 211, 154, 48, 184, 164, 51, 40, 19, 226, 191, 148, 229, 143, 234, 200, 160, 249, 6, 22, 133, 4, 232, 83, 16, 27, 86, 33, 122, 154, 12, 57, 166, 219, 133, 30, 24, 197, 172, 234, 217, 62, 132, 154, 127, 92, 195, 189, 150, 77, 219, 217, 227, 183, 179, 213, 72, 50, 155, 16, 80, 64, 22, 163, 222, 252, 104, 83, 0, 48, 3, 204], "timestamp": 1970-01-01T00:00:00.000Z, "version": 1}
```

### CODE REVIEW

**Comment by bricestacey** [comment]
I was able to pull this from logcat.. Looks like the message might be too large? 

My payload is only `msg.payload = new Uint8Array([1, 2, 3, 4, 5]);`

```
gowaku.node2.store	store/waku_store_client.go:254	waku.store retrieved	{"hashes": ["0xe87c5aebbdea0564197d09afb9178fec58bfda1a7836b285a5cf03bee68f2875"]}
02-08 15:45:45.458  5663  5867 I ReactNativeJS: { payload: 
02-08 15:45:45.458  5663  5867 I ReactNativeJS:    { '0': 4,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '1': 22,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '2': 188,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '3': 181,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '4': 148,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '5': 94,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '6': 23,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '7': 190,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '8': 75,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '9': 30,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '10': 248,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '11': 213,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '12': 160,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '13': 82,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '14': 23,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '15': 132,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '16': 225,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '17': 25,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '18': 82,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '19': 142,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '20': 47,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '21': 90,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '22': 101,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '23': 178,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '24': 224,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '25': 171,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '26': 94,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '27': 252,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '28': 59,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '29': 43,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '30': 160,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '31': 171,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '32': 127,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '33': 44,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '34': 7,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '35': 65,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '36': 30,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '37': 76,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '38': 178,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '39': 194,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '40': 110,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '41': 195,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '42': 203,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '43': 65,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '44': 220,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '45': 43,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '46': 190,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '47': 250,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '48': 179,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '49': 64,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '50': 85,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '51': 78,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '52': 115,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '53': 5,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '54': 106,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '55': 12,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '56': 149,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '57': 135,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '58': 248,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '59': 239,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '60': 116,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '61': 2,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '62': 4,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '63': 178,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '64': 74,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '65': 123,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '66': 124,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '67': 252,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '68': 230,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '69': 104,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '70': 86,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '71': 53,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '72': 18,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '73': 222,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '74': 206,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '75': 109,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '76': 179,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '77': 53,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '78': 141,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '79': 255,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '80': 204,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '81': 139,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '82': 30,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '83': 1,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '84': 236,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '85': 156,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '86': 75,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '87': 236,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '88': 40,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '89': 252,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '90': 117,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '91': 224,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '92': 155,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '93': 246,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '94': 184,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '95': 77,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '96': 22,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '97': 141,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '98': 241,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '99': 51,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '100': 234,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '101': 32,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '102': 118,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '103': 241,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '104': 159,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '105': 109,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '106': 93,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '107': 39,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '108': 193,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '109': 27,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '110': 15,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '111': 39,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '112': 83,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '113': 25,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '114': 23,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '115': 12,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '116': 104,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '117': 88,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '118': 108,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '119': 242,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '120': 193,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '121': 79,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '122': 161,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '123': 55,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '124': 205,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '125': 41,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '126': 67,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '127': 22,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '128': 146,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '129': 12,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '130': 104,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '131': 68,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '132': 127,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '133': 10,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '134': 109,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '135': 190,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '136': 42,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '137': 151,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '138': 72,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '139': 3,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '140': 13,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '141': 43,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '142': 0,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '143': 201,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '144': 153,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '145': 198,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '146': 32,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '147': 2,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '148': 177,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '149': 223,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '150': 43,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '151': 102,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '152': 234,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '153': 148,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '154': 12,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '155': 108,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '156': 202,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '157': 230,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '158': 76,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '159': 20,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '160': 140,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '161': 188,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '162': 208,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '163': 36,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '164': 131,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '165': 237,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '166': 166,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '167': 245,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '168': 71,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '169': 77,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '170': 156,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '171': 99,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '172': 111,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '173': 81,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '174': 239,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '175': 218,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '176': 127,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '177': 121,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '178': 141,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '179': 14,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '180': 189,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '181': 244,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '182': 110,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '183': 10,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '184': 16,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '185': 154,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '186': 101,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '187': 154,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '188': 161,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '189': 33,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '190': 103,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '191': 18,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '192': 166,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '193': 50,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '194': 55,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '195': 188,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '196': 63,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '197': 154,
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '198': [TOO BIG formatValueCalls 201 exceeded limit of 200],
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '199': [TOO BIG formatValueCalls 202 exceeded limit of 200],
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '200': [TOO BIG formatValueCalls 203 exceeded limit of 200],
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '201': [TOO BIG formatValueCalls 204 exceeded limit of 200],
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '202': [TOO BIG formatValueCalls 205 exceeded limit of 200],
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '203': [TOO BIG formatValueCalls 206 exceeded limit of 200],
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '204': [TOO BIG formatValueCalls 207 exceeded limit of 200],
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '205': [TOO BIG formatValueCalls 208 exceeded limit of 200],
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '206': [TOO BIG formatValueCalls 209 exceeded limit of 200],
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '207': [TOO BIG formatValueCalls 210 exceeded limit of 200],
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '208': [TOO BIG formatValueCalls 211 exceeded limit of 200],
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '209': [TOO BIG formatValueCalls 212 exceeded limit of 200],
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '210': [TOO BIG formatValueCalls 213 exceeded limit of 200],
02-08 15:45:45.458  5663  5867 I ReactNativeJS:      '211': [TOO BIG formatValueCalls 214 exceeded limit of 200
02-08 15:45:45.889   342  5876 D resolv  : GetAddrInfoHandler::run: {101 101 101 983141 10148 0}
02-08 15:45:45.889   342  5876 D resolv  : resolv_getaddrinfo: explore_fqdn(): ai_family=0 ai_socktype=1 ai_protocol=6
02-08 15:45:45.889   342  5876 D resolv  : android_getaddrinfofornetcontext: explore_numeric: ai_family=10 ai_socktype=1 ai_protocol=6
02-08 15:45:45.889   342  5876 D resolv  : explore_numeric_scope
02-08 15:45:45.889   342  5876 D resolv  : android_getaddrinfofornetcontext: explore_numeric: ai_family=2 ai_socktype=1 ai_protocol=6
02-08 15:45:45.889   342  5876 D resolv  : explore_numeric_scope
02-08 15:45:46.264   342   342 I netd    : trafficSwapActiveStatsMap() <28.76ms>
02-08 15:45:46.268   342   342 I netd    : tetherGetStats() -> {[]} <2.08ms>
02-08 15:45:46.271   342   342 I netd    : bandwidthSetGlobalAlert(2097152) <0.16ms>
02-08 15:45:46.275   342   342 I netd    : bandwidthRemoveInterfaceQuota(eth0) <1.16ms>
02-08 15:45:46.277   342   342 I netd    : bandwidthSetInterfaceQuota(eth0, 9223372036854775807) <1.47ms>
02-08 15:45:46.311   342   342 I netd    : trafficSwapActiveStatsMap() <29.31ms>
02-08 15:45:46.312   342   342 I netd    : tetherGetStats() -> {[]} <0.91ms>
02-08 15:45:46.316   342   342 I netd    : bandwidthRemoveInterfaceQuota(eth0) <0.69ms>
02-08 15:45:46.317   342   342 I netd    : bandwidthSetInterfaceQuota(eth0, 9223372036854775807) <0.90ms>
02-08 15:45:47.469  5663  5867 W ReactNativeJS: Possible Unhandled Promise Rejection (id: 0):
02-08 15:45:47.469  5663  5867 W ReactNativeJS: "json: cannot unmarshal object into Go struct field WakuMessage.payload of type []uint8"
```

**Comment by bricestacey** [comment]
That looks like a RN/iOS warning, doesn't look relevant

**Comment by bricestacey** [comment]
I was actually able to solve this. I will follow up once I can clean it up a bit, probably by tomorrow.

**Comment by bricestacey** [comment]
This PR includes a couple fixes:

1. Adds missing pods script in the example project.
2. Replaces base-64 with Buffer.
3. Fixes a typo where asymmetric decoding was calling `decodeSymmetric` by accident

With this, my test case found here https://github.com/waku-org/waku-react-native/compare/master...bricestacey:waku-react-native:encrypt-bug works just fine.

**Review by richard-ramos — APPROVED** [review]
Thank you very much for this PR!

**Pull request merged**
